
manufacturer_options = ["other", "ford", "chevrolet", "toyota", "honda", "jeep", "nissan", "ram", "gmc", "bmw", "dodge", "mercedes-benz", "hyundai", "subaru", "volkswagen", "kia", "lexus", "audi", "cadillac", "acura", "chrysler"]

regions_options = ["other", 'Columbus',
 'Jacksonville',
 'Reno/Tahoe',
 'Grand Rapids',
 'Boise',
 'Tulsa',
 'South Jersey',
 'Spokane/Coeur d\'Alene',
 'Houston',
 'Rochester',
 'New Hampshire',
 'Portland, ME',
 'Sacramento',
 'Pittsburgh',
 'Baltimore',
 'Bend',
 'Albuquerque',
 'Long Island',
 'Cleveland',
 'New York City',
 'Tucson',
 'Minneapolis/St. Paul',
 'Stockton',
 'Norfolk/Hampton Roads',
 'Washington, DC',
 'Kansas City, MO',
 'San Francisco Bay Area',
 'Boston',
 'Maine',
 'Tampa Bay Area',
 'Sarasota-Bradenton',
 'Orlando',
 'Milwaukee',
 'Seattle-Tacoma',
 'Austin',
 'Salem',
 'Philadelphia',
 'Des Moines',
 'Denver',
 'Phoenix',
 'Eugene',
 'Fresno/Madera',
 'Colorado Springs',
 'Las Vegas',
 'St. Louis, MO',
 'Orange County',
 'Detroit Metro',
 'Los Angeles',
 'Oklahoma City',
 'Chicago']

vehicle_condition_options = ["Excellent", "Good", "Fair", "New", "Like new", "Salvage"]

fuel_options = ["Gas", "Diesel", "Hybrid", "Electric", "Other"]

title_status_options = ["Clean", "Rebuilt", "Salvage", "Lien", "Parts Only"]

transmission_options = ["Automatic", "Manual", "Other"]

vehicle_sizes = ["full-size", "compact", "mid-size", "sub-compact"]

colors = ["white", "black", "silver", "blue", "red", "grey", "green", "brown", "custom", "orange", "yellow", "purple"]

type = ['sedan',
'suv',
'pickup',
'truck',
'other',
'coupe',
'hatchback',
'wagon',
'van',
'convertible',
'mini-van',
'offroad',
'bus']

size = ['full-size','mid-size','compact','sub-compact','uncharted']

models=['F-150',
'Silverado 1500',
'1500',
'Camry',
'Silverado',
'Accord',
'Civic',
'Wrangler',
'Escape',
'Altima',
'2500',
'Tacoma',
'Explorer',
'Grand Cherokee',
'Corolla',
'Mustang',
'Equinox',
'Fusion',
'CR-V',
'Focus',
'Malibu',
'Charger',
'Tahoe',
'RAV4',
'Sonata',
'Corvette',
'Impala',
'Sierra 1500',
'Grand Caravan',
'Outback',
'Cruze',
'F-250',
'Silverado 2500HD',
'Elantra',
'3500',
'Odyssey',
'Edge',
'Prius',
'Tundra',
'Jetta',
'Forester',
'Rogue',
'Sierra',
'Wrangler Unlimited',
'Sentra',
'Camaro',
'Soul',
'F-350',
'Sienna',
'Pilot']

regions_options = ["other", 'Columbus',
 'Jacksonville',
 'Reno/Tahoe',
 'Grand Rapids',
 'Boise',
 'Tulsa',
 'South Jersey',
 'Spokane/Coeur d\'Alene',
 'Houston',
 'Rochester',
 'New Hampshire',
 'Portland, ME',
 'Sacramento',
 'Pittsburgh',
 'Baltimore',
 'Bend',
 'Albuquerque',
 'Long Island',
 'Cleveland',
 'New York City',
 'Tucson',
 'Minneapolis/St. Paul',
 'Stockton',
 'Norfolk/Hampton Roads',
 'Washington, DC',
 'Kansas City, MO',
 'San Francisco Bay Area',
 'Boston',
 'Maine',
 'Tampa Bay Area',
 'Sarasota-Bradenton',
 'Orlando',
 'Milwaukee',
 'Seattle-Tacoma',
 'Austin',
 'Salem',
 'Philadelphia',
 'Des Moines',
 'Denver',
 'Phoenix',
 'Eugene',
 'Fresno/Madera',
 'Colorado Springs',
 'Las Vegas',
 'St. Louis, MO',
 'Orange County',
 'Detroit Metro',
 'Los Angeles',
 'Oklahoma City',
 'Chicago']

state=['ca',
'fl',
'tx',
'ny',
'oh',
'or',
'mi',
'nc',
'pa',
'wa',
'wi',
'tn',
'co',
'va',
'il',
'nj',
'id',
'az',
'ia',
'ma',
'mn',
'ga',
'ok',
'ks',
'mt',
'sc',
'in',
'ct',
'md',
'al',
'mo',
'nm',
'ky',
'ar',
'ak',
'la',
'nv',
'nh',
'dc',
'me',
'hi',
'vt',
'ri',
'sd',
'ut',
'wv',
'ms',
'de',
'ne',
'wy',
'nd',]

drive_options = ["4wd", "fwd", "rwd", "uncharted"]




